In [1]:
import os
import scipy.io
import numpy as np
import pandas as pd

In [2]:
meta_data=scipy.io.loadmat('/Users/daish/Downloads/imdb 2/imdb.mat')
print(meta_data.keys())
imdb_set=meta_data["imdb"] #this is not just accessing key but it has become a np array
print(imdb_set)
#is output me dekho array ke piche 2 brackets hai mtlb [0][0] ya .squeeze

dict_keys(['__header__', '__version__', '__globals__', 'imdb'])
[[(array([[693726, 693726, 693726, ..., 726831, 726831, 726831]], dtype=int32), array([[1968, 1970, 1968, ..., 2011, 2011, 2011]], dtype=uint16), array([[array(['01/nm0000001_rm124825600_1899-5-10_1968.jpg'], dtype='<U43'),
          array(['01/nm0000001_rm3343756032_1899-5-10_1970.jpg'], dtype='<U44'),
          array(['01/nm0000001_rm577153792_1899-5-10_1968.jpg'], dtype='<U43'),
          ...,
          array(['08/nm3994408_rm926592512_1989-12-29_2011.jpg'], dtype='<U44'),
          array(['08/nm3994408_rm943369728_1989-12-29_2011.jpg'], dtype='<U44'),
          array(['08/nm3994408_rm976924160_1989-12-29_2011.jpg'], dtype='<U44')]],
        dtype=object), array([[1., 1., 1., ..., 0., 0., 0.]]), array([[array(['Fred Astaire'], dtype='<U12'),
          array(['Fred Astaire'], dtype='<U12'),
          array(['Fred Astaire'], dtype='<U12'), ...,
          array(['Jane Levy'], dtype='<U9'),
          array(['Jane Levy'], dt

In [3]:
print(imdb_set.shape)
type(imdb_set)
# so now to access this ndarray either we can use imdb_set[0][0] or .squeeze() 
imdb_set=imdb_set.squeeze()[()]
print(imdb_set)
#basically ab we can access this struct directly and to know its fields we pass .dtype




(1, 1)
(array([[693726, 693726, 693726, ..., 726831, 726831, 726831]], dtype=int32), array([[1968, 1970, 1968, ..., 2011, 2011, 2011]], dtype=uint16), array([[array(['01/nm0000001_rm124825600_1899-5-10_1968.jpg'], dtype='<U43'),
        array(['01/nm0000001_rm3343756032_1899-5-10_1970.jpg'], dtype='<U44'),
        array(['01/nm0000001_rm577153792_1899-5-10_1968.jpg'], dtype='<U43'),
        ...,
        array(['08/nm3994408_rm926592512_1989-12-29_2011.jpg'], dtype='<U44'),
        array(['08/nm3994408_rm943369728_1989-12-29_2011.jpg'], dtype='<U44'),
        array(['08/nm3994408_rm976924160_1989-12-29_2011.jpg'], dtype='<U44')]],
      dtype=object), array([[1., 1., 1., ..., 0., 0., 0.]]), array([[array(['Fred Astaire'], dtype='<U12'),
        array(['Fred Astaire'], dtype='<U12'),
        array(['Fred Astaire'], dtype='<U12'), ...,
        array(['Jane Levy'], dtype='<U9'),
        array(['Jane Levy'], dtype='<U9'),
        array(['Jane Levy'], dtype='<U9')]], dtype=object), array([[a

In [4]:
print(type(imdb_set))             # Should be <class 'numpy.ndarray'>
print(imdb_set.dtype)             # Should list 'dob', 'photo_taken', etc.
print(imdb_set['dob'][:10])        # First 5 date of birth serials
print(imdb_set['photo_taken'][:5]) # First 5 photo_taken years
print(imdb_set['gender'])

<class 'numpy.void'>
[('dob', 'O'), ('photo_taken', 'O'), ('full_path', 'O'), ('gender', 'O'), ('name', 'O'), ('face_location', 'O'), ('face_score', 'O'), ('second_face_score', 'O'), ('celeb_names', 'O'), ('celeb_id', 'O')]
[[693726 693726 693726 ... 726831 726831 726831]]
[[1968 1970 1968 ... 2011 2011 2011]]
[[1. 1. 1. ... 0. 0. 0.]]


In [5]:
print(imdb_set.dtype)
dob_serial= imdb_set['dob']
photo_taken = imdb_set['photo_taken']
full_path = imdb_set['full_path'].squeeze()
gender = imdb_set['gender'].squeeze()
face_score = imdb_set['face_score'].squeeze()
second_face_score = imdb_set['second_face_score'].squeeze()

[('dob', 'O'), ('photo_taken', 'O'), ('full_path', 'O'), ('gender', 'O'), ('name', 'O'), ('face_location', 'O'), ('face_score', 'O'), ('second_face_score', 'O'), ('celeb_names', 'O'), ('celeb_id', 'O')]


In [6]:
'''from datetime import datetime, timedelta

def matlab_serial_to_date(serial):
    # MATLAB's reference date is January 1, 0000
    base_date = datetime(1, 1, 1)  # MATLAB's starting point
    return base_date + timedelta(days=serial - 366)  # Adjust for MATLAB leap year bug

def calculate_age(dob_serial, photo_year):
    dob = matlab_serial_to_date(dob_serial)
    # Assume photo taken on July 1st for age calculation
    photo_date = datetime(photo_year, 7, 1)
    age = photo_date.year - dob.year
    if dob.month > photo_date.month or (dob.month == photo_date.month and dob.day > photo_date.day):
        age -= 1
    return age

# Example usage
dob_serial = 693726  # Serial value to test
photo_year = 1970  # Year the photo was taken

dob = matlab_serial_to_date(dob_serial)
age = calculate_age(dob_serial, photo_year)

print(f"DOB: {dob}")
print(f"Calculated Age: {age}
'''
 

'from datetime import datetime, timedelta\n\ndef matlab_serial_to_date(serial):\n    # MATLAB\'s reference date is January 1, 0000\n    base_date = datetime(1, 1, 1)  # MATLAB\'s starting point\n    return base_date + timedelta(days=serial - 366)  # Adjust for MATLAB leap year bug\n\ndef calculate_age(dob_serial, photo_year):\n    dob = matlab_serial_to_date(dob_serial)\n    # Assume photo taken on July 1st for age calculation\n    photo_date = datetime(photo_year, 7, 1)\n    age = photo_date.year - dob.year\n    if dob.month > photo_date.month or (dob.month == photo_date.month and dob.day > photo_date.day):\n        age -= 1\n    return age\n\n# Example usage\ndob_serial = 693726  # Serial value to test\nphoto_year = 1970  # Year the photo was taken\n\ndob = matlab_serial_to_date(dob_serial)\nage = calculate_age(dob_serial, photo_year)\n\nprint(f"DOB: {dob}")\nprint(f"Calculated Age: {age}\n'

In [7]:
from datetime import datetime,timedelta

def age_cal(dob_serial,photo_taken):
    if np.isnan(dob_serial) or np.isnan(photo_taken) or dob_serial <= 366:
        return np.nan
    ref_date=datetime(1,1,1)
    dob=ref_date+timedelta(days=int(dob_serial)-366)
    
    photo_taken=datetime(photo_taken,7,1)
    age=photo_taken.year-dob.year

    if dob.month>photo_taken.month or (dob.month==photo_taken.month and dob.day>photo_taken.day):
        age-=1
    return age

    


In [8]:
dob_serial=dob_serial.squeeze()
photo_taken=photo_taken.squeeze()
print(dob_serial)

[693726 693726 693726 ... 726831 726831 726831]


In [9]:
ages=[age_cal(d,p) for d,p in zip(dob_serial,photo_taken)]
print(ages)

[69, 71, 69, 69, 69, 66, 79, 79, 66, 79, 83, 66, 49, 82, 49, 81, 81, 81, 81, 79, 63, 79, 49, 82, 49, 80, 82, 82, 80, 83, 82, 66, 81, 81, 85, 83, 65, 79, 79, 66, 49, 66, 79, 81, 80, 66, 31, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 27, 27, 27, 27, 29, 29, 29, 29, 29, 32, 32, 32, 32, 29, 32, 84, 84, 84, 84, 53, 53, 53, 53, 58, 58, 53, 53, 62, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 39, 39, 39, 39, 39, 39, 39, 39, 77, 72, 66, 86, 66, 66, 66, 70, 66, 66, 42, 55, 43, 53, 87, 40, 66, 72, 72, 52, 52, 52, 77, 52, 70, 48, 48, 48, 48, 70, 70, 66, 55, 66, 54, 72, 37, 37, 46, 42, 52, 37, 40, 40, 40, 37, 37, 37, 37, 43, 37, 43, 43, 43, 37, 43, 43, 43, 37, 43, 37, 43, 42, 37, 37, 58, 58, 38, 43, 43, 43, 43, 37, 58, 51, 38, 51, 38, 58, 38, 38, 51, 58, 51, 37, 58, 38, 37, 37, 81, 61, 61, 61, 81, 61, 61, 61, 61, 61, 61, 70, 54, 54, 54, 54, 54, 70, 70, 70, 54, 54, 70, 39, 44, 41, 41, 44, 44, 44, 44, 41, 44, 40, 42, 39, 40, 40, 40, 40, 40, 40, 59, 59, 77,

In [10]:
df=pd.DataFrame({
    'ages':ages,
    'photo_year':photo_taken,
    'gender':gender,
    'face_score':face_score,
    'second_face_score':second_face_score,
    'full_path':full_path
    

})
df.head()

ages  photo_year  gender  face_score  second_face_score  \
0  69.0        1968     1.0    1.459693           1.118973   
1  71.0        1970     1.0    2.543198           1.852008   
2  69.0        1968     1.0    3.455579           2.985660   
3  69.0        1968     1.0    1.872117                NaN   
4  69.0        1968     1.0    1.158766                NaN   

                                        full_path  
0   [01/nm0000001_rm124825600_1899-5-10_1968.jpg]  
1  [01/nm0000001_rm3343756032_1899-5-10_1970.jpg]  
2   [01/nm0000001_rm577153792_1899-5-10_1968.jpg]  
3   [01/nm0000001_rm946909184_1899-5-10_1968.jpg]  
4   [01/nm0000001_rm980463616_1899-5-10_1968.jpg]

In [11]:
# 2 df isliye use hue hai jisse poora database aa paye agar do facescore use karte to database se sirf wahi columns select hojate


In [12]:
df=df.dropna(subset=['gender','ages','photo_year'])
df=df[df['face_score']>1]
df=df[df['second_face_score'].isna()]
df=df[(df['ages']>=0) & (df['ages']<=100)]
df.head()


ages  photo_year  gender  face_score  second_face_score  \
3   69.0        1968     1.0    1.872117                NaN   
4   69.0        1968     1.0    1.158766                NaN   
6   79.0        2004     0.0    3.479189                NaN   
7   79.0        2004     0.0    3.870171                NaN   
12  49.0        1974     0.0    4.096431                NaN   

                                         full_path  
3    [01/nm0000001_rm946909184_1899-5-10_1968.jpg]  
4    [01/nm0000001_rm980463616_1899-5-10_1968.jpg]  
6   [02/nm0000002_rm1346607872_1924-9-16_2004.jpg]  
7   [02/nm0000002_rm1363385088_1924-9-16_2004.jpg]  
12   [02/nm0000002_rm221957120_1924-9-16_1974.jpg]

In [13]:
print(df['full_path'].apply(type).head())
df['full_path']=df['full_path'].apply(lambda x:x[0] if isinstance(x, np.ndarray) else x)
df.head()


3     <class 'numpy.ndarray'>
4     <class 'numpy.ndarray'>
6     <class 'numpy.ndarray'>
7     <class 'numpy.ndarray'>
12    <class 'numpy.ndarray'>
Name: full_path, dtype: object


ages  photo_year  gender  face_score  second_face_score  \
3   69.0        1968     1.0    1.872117                NaN   
4   69.0        1968     1.0    1.158766                NaN   
6   79.0        2004     0.0    3.479189                NaN   
7   79.0        2004     0.0    3.870171                NaN   
12  49.0        1974     0.0    4.096431                NaN   

                                       full_path  
3    01/nm0000001_rm946909184_1899-5-10_1968.jpg  
4    01/nm0000001_rm980463616_1899-5-10_1968.jpg  
6   02/nm0000002_rm1346607872_1924-9-16_2004.jpg  
7   02/nm0000002_rm1363385088_1924-9-16_2004.jpg  
12   02/nm0000002_rm221957120_1924-9-16_1974.jpg

In [14]:
# much easier one liner way for above processes
'''df = (
    df.dropna(subset=['gender', 'ages', 'photo_year'])
      .query('face_score > 1')
      .query('second_face_score != second_face_score')  # NaN != NaN trick
      .query('0 <= ages <= 100')
)'''

"df = (\n    df.dropna(subset=['gender', 'ages', 'photo_year'])\n      .query('face_score > 1')\n      .query('second_face_score != second_face_score')  # NaN != NaN trick\n      .query('0 <= ages <= 100')\n)"

In [15]:
df.to_csv("cleaned_imdb")

In [18]:
df.head()

ages  photo_year  gender  face_score  second_face_score  \
3   69.0        1968     1.0    1.872117                NaN   
4   69.0        1968     1.0    1.158766                NaN   
6   79.0        2004     0.0    3.479189                NaN   
7   79.0        2004     0.0    3.870171                NaN   
12  49.0        1974     0.0    4.096431                NaN   

                                       full_path  
3    01/nm0000001_rm946909184_1899-5-10_1968.jpg  
4    01/nm0000001_rm980463616_1899-5-10_1968.jpg  
6   02/nm0000002_rm1346607872_1924-9-16_2004.jpg  
7   02/nm0000002_rm1363385088_1924-9-16_2004.jpg  
12   02/nm0000002_rm221957120_1924-9-16_1974.jpg